version: '2.2'

services:

  proxy:
    image: silvanwmde/nginx-proxy:latest
    hostname: proxy.localhost
    environment:
      - VIRTUAL_HOST=proxy.localhost
      - HOSTNAMES=.demo.localhost      # wildcard name resolution, thanks to DPS
    ports:
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      dps:
        ipv4_address: 172.0.0.10

  demo:
    image: nginxdemos/hello:plain-text
    hostname: demo.localhost
    depends_on:
      - proxy
    environment:
      - VIRTUAL_HOST=*.demo.localhost
      - VIRTUAL_PORT=80
    ports:
      - 9090:8080
    networks:
      - dps

networks:
  dps:
    ipam:
      config:
        - subnet: 172.0.0.0/24
